"""remove filename field

Revision ID: 54cb17bcce70
Revises: d97f21d3acd1
Create Date: 2025-06-24 18:33:23.500984+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54cb17bcce70"
down_revision: Union[str, None] = "d97f21d3acd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
