"""add s3 object key to doc

Revision ID: 1a97ec600e2b
Revises: 08ee6d365f2d
Create Date: 2025-04-12 05:45:31.380629+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a97ec600e2b"
down_revision: Union[str, None] = "08ee6d365f2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("s3_object_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "s3_object_key")
    # ### end Alembic commands ###
