"""store size_in_kb per paper

Revision ID: 16fc429323a5
Revises: b441e42dd8ad
Create Date: 2025-07-05 03:20:37.512882+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16fc429323a5"
down_revision: Union[str, None] = "b441e42dd8ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("size_in_kb", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "size_in_kb")
    # ### end Alembic commands ###
