"""deletable documents

Revision ID: f18a90deb64f
Revises: 38580605ef33
Create Date: 2025-04-05 23:25:36.357838+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f18a90deb64f"
down_revision: Union[str, None] = "38580605ef33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "annotations_document_id_fkey", "annotations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "annotations", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "conversations_document_id_fkey", "conversations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "conversations", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("highlights_document_id_fkey", "highlights", type_="foreignkey")
    op.create_foreign_key(
        None, "highlights", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "paper_notes_document_id_fkey", "paper_notes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "paper_notes", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "paper_notes", type_="foreignkey")
    op.create_foreign_key(
        "paper_notes_document_id_fkey",
        "paper_notes",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.drop_constraint(None, "highlights", type_="foreignkey")
    op.create_foreign_key(
        "highlights_document_id_fkey",
        "highlights",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.create_foreign_key(
        "conversations_document_id_fkey",
        "conversations",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.drop_constraint(None, "annotations", type_="foreignkey")
    op.create_foreign_key(
        "annotations_document_id_fkey",
        "annotations",
        "documents",
        ["document_id"],
        ["id"],
    )
    # ### end Alembic commands ###
