"""paper image placeholder

Revision ID: fca22e49419f
Revises: cb874d6c3557
Create Date: 2025-07-11 03:01:58.198299+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fca22e49419f"
down_revision: Union[str, None] = "cb874d6c3557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paper_images", sa.Column("placeholder_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_images", "placeholder_id")
    # ### end Alembic commands ###
