"""paper upload job

Revision ID: fa2170054d6f
Revises: 75b2484de153
Create Date: 2025-06-06 21:06:54.923605+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa2170054d6f"
down_revision: Union[str, None] = "75b2484de153"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_upload_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("hypothesis_jobs", "job_type")
    op.add_column("papers", sa.Column("upload_job_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "papers",
        "paper_upload_jobs",
        ["upload_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "papers", type_="foreignkey")
    op.drop_column("papers", "upload_job_id")
    op.add_column(
        "hypothesis_jobs",
        sa.Column("job_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_table("paper_upload_jobs")
    # ### end Alembic commands ###
