"""task_id for paperuploadjob

Revision ID: d97f21d3acd1
Revises: 4c8dd22b9782
Create Date: 2025-06-24 01:16:03.709530+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d97f21d3acd1"
down_revision: Union[str, None] = "4c8dd22b9782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paper_upload_jobs", sa.Column("task_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_upload_jobs", "task_id")
    # ### end Alembic commands ###
