"""let papers be publicly shareable

Revision ID: cc8347c1bf8a
Revises: e70660c9cdeb
Create Date: 2025-04-30 05:45:21.894394+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc8347c1bf8a"
down_revision: Union[str, None] = "e70660c9cdeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("is_public", sa.Boolean(), nullable=True))
    op.add_column("papers", sa.Column("share_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_papers_share_id"), "papers", ["share_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_papers_share_id"), table_name="papers")
    op.drop_column("papers", "share_id")
    op.drop_column("papers", "is_public")
    # ### end Alembic commands ###
