"""paper status track

Revision ID: c8272547800a
Revises: 506620d8855a
Create Date: 2025-06-01 03:45:25.434660+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8272547800a"
down_revision: Union[str, None] = "506620d8855a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("status", sa.String(), nullable=True))

    # Update all existing records to have 'reading' status
    op.execute("UPDATE papers SET status = 'reading' WHERE status IS NULL")

    # Set 'status' column to not nullable
    op.alter_column("papers", "status", nullable=False, existing_type=sa.String())

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "status")
    # ### end Alembic commands ###
