"""specify deletion logic for conversation - message relationship

Revision ID: 28a21d44f5ad
Revises: cc8347c1bf8a
Create Date: 2025-05-17 00:26:21.190887+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28a21d44f5ad"
down_revision: Union[str, None] = "cc8347c1bf8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
