"""paper cache presigned url

Revision ID: 506620d8855a
Revises: d4254461a57e
Create Date: 2025-05-28 04:31:47.287092+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "506620d8855a"
down_revision: Union[str, None] = "d4254461a57e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers", sa.Column("cached_presigned_url", sa.String(), nullable=True)
    )
    op.add_column(
        "papers",
        sa.Column(
            "presigned_url_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "presigned_url_expires_at")
    op.drop_column("papers", "cached_presigned_url")
    # ### end Alembic commands ###
