"""expand documents

Revision ID: a0f907885224
Revises: 3b4caa2f130a
Create Date: 2025-03-24 01:13:40.817621+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f907885224'
down_revision: Union[str, None] = '3b4caa2f130a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('institutions', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'date')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'keywords')
    op.drop_column('documents', 'institutions')
    op.drop_column('documents', 'abstract')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'authors')
    # ### end Alembic commands ###
