"""paper last_accessed_At

Revision ID: ba50a2b21707
Revises: c8272547800a
Create Date: 2025-06-03 23:26:41.372672+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba50a2b21707"
down_revision: Union[str, None] = "c8272547800a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Set default value of last_accessed_at to updated_at for existing records
    op.execute(
        "UPDATE papers SET last_accessed_at = updated_at WHERE last_accessed_at IS NULL"
    )

    # Make last_accessed_at non-nullable and set server default to now()
    op.alter_column(
        "papers",
        "last_accessed_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        existing_nullable=True,
        server_default=sa.text("now()"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "last_accessed_at")
    # ### end Alembic commands ###
