"""split artifacts into typed tables per kind

Artifacts were one table with a JSONB payload holding every kind. Each kind now
has its own table under a joined-table hierarchy, so its shape is declared once
in the schema instead of in whichever code last read it.

The two kinds are treated differently on purpose. Citations are live in
production and are carried across field by field, with a count check that
aborts the migration rather than let one go missing. Charts have never shipped,
so their rows are dropped instead of translated.

Revision ID: e79fd911cb1e
Revises: 7d0f8cddd5db
Create Date: 2026-08-19 19:12:33.632592+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e79fd911cb1e"
down_revision: Union[str, None] = "7d0f8cddd5db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chart_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("chart_type", sa.String(), nullable=False),
        sa.Column("series_by_paper", sa.Boolean(), nullable=False),
        sa.Column("calculation_label", sa.String(), nullable=True),
        sa.Column("calculation_spec", sa.Text(), nullable=True),
        sa.Column("calculation_inputs", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("searched_paper_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("included_paper_ids", sa.ARRAY(sa.UUID()), nullable=False),
        sa.Column("warnings", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("extraction_steps", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "computation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "conversions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "investigation_trace",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "citation_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("preferred_style", sa.String(), nullable=False),
        sa.Column("style_display", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("missing_fields", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("authors", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("publish_date", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citation_artifacts_paper_id"),
        "citation_artifacts",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "chart_excluded_papers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chart_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chart_id"], ["chart_artifacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chart_id", "paper_id", name="uq_chart_excluded_paper"),
    )
    op.create_index(
        op.f("ix_chart_excluded_papers_chart_id"),
        "chart_excluded_papers",
        ["chart_id"],
        unique=False,
    )
    op.create_table(
        "chart_fields",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chart_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chart_id"], ["chart_artifacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chart_id", "role", "key", name="uq_chart_fields_role_key"),
    )
    op.create_index(
        op.f("ix_chart_fields_chart_id"), "chart_fields", ["chart_id"], unique=False
    )
    op.create_table(
        "chart_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chart_id", sa.UUID(), nullable=False),
        sa.Column("record_key", sa.String(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("paper_title", sa.String(), nullable=False),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chart_id"], ["chart_artifacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chart_id", "record_key", name="uq_chart_records_key"),
    )
    op.create_index(
        op.f("ix_chart_records_chart_id"), "chart_records", ["chart_id"], unique=False
    )
    op.create_index(
        op.f("ix_chart_records_paper_id"), "chart_records", ["paper_id"], unique=False
    )
    op.create_table(
        "chart_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("line_number", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("conversion", sa.Text(), nullable=False),
        sa.Column("conversion_note", sa.Text(), nullable=True),
        sa.Column("number", sa.Float(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["chart_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "key", name="uq_chart_values_key"),
    )
    op.create_index(
        op.f("ix_chart_values_record_id"), "chart_values", ["record_id"], unique=False
    )
    # ### end Alembic commands ###

    # Held for the copy, the count check, and the drop of `payload` together.
    # The old code is still writing payload while this runs, and a citation
    # committed between the check and the drop would lose its body without the
    # check ever seeing it — the one case the check exists to prevent and the
    # one case it cannot observe on its own. drop_column takes this same lock
    # regardless, so this only moves it earlier.
    op.execute("LOCK TABLE artifacts IN ACCESS EXCLUSIVE MODE")

    # Citations are shipped. Carry every one across, reading each field
    # defensively so an older payload missing a key costs that field and not
    # the row.
    op.execute(
        """
        INSERT INTO citation_artifacts (
            id, paper_id, preferred_style, style_display, method, confidence,
            missing_fields, title, authors, publish_date, journal, publisher, doi
        )
        SELECT
            a.id,
            (a.payload->>'paper_id')::uuid,
            COALESCE(a.payload->>'preferred_style', ''),
            COALESCE(a.payload->>'style_display', ''),
            COALESCE(a.payload->>'method', ''),
            (a.payload->>'confidence')::double precision,
            CASE
                WHEN jsonb_typeof(a.payload->'missing_fields') = 'array'
                THEN ARRAY(SELECT jsonb_array_elements_text(a.payload->'missing_fields'))
                ELSE '{}'::text[]
            END,
            a.payload->'data'->>'title',
            CASE
                WHEN jsonb_typeof(a.payload->'data'->'authors') = 'array'
                THEN ARRAY(SELECT jsonb_array_elements_text(a.payload->'data'->'authors'))
                ELSE '{}'::text[]
            END,
            a.payload->'data'->>'publish_date',
            a.payload->'data'->>'journal',
            a.payload->'data'->>'publisher',
            a.payload->'data'->>'doi'
        FROM artifacts a
        WHERE a.kind = 'citation'
          AND a.payload->>'paper_id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        """
    )

    # A citation that did not make it across would come back from the API as an
    # artifact with no body. Stop here instead: losing a user's saved citation
    # silently is worse than a failed deploy.
    op.execute(
        """
        DO $$
        DECLARE missing integer;
        BEGIN
            SELECT count(*) INTO missing
            FROM artifacts a
            LEFT JOIN citation_artifacts c ON c.id = a.id
            WHERE a.kind = 'citation' AND c.id IS NULL;
            IF missing > 0 THEN
                RAISE EXCEPTION
                    'Could not migrate % citation artifact(s); their paper_id is not a uuid', missing;
            END IF;
        END $$;
        """
    )

    # Charts have never shipped, so there is nothing to preserve. The job and
    # the chart it produced are one unit, so a job whose result is dropped goes
    # with it rather than being left pointing at nothing.
    op.execute(
        """
        DELETE FROM chart_generation_jobs
        WHERE artifact_id IN (SELECT id FROM artifacts WHERE kind = 'chart')
        """
    )
    op.execute("DELETE FROM artifacts WHERE kind = 'chart'")

    op.drop_column("artifacts", "payload")

    # Where the reviewer's objection to a nullable message_id is actually
    # answered: a citation is always a reply to something a user asked, so it
    # always has one. A chart may be raised by a background job that has no
    # conversation at all, so for that kind the column is genuinely optional.
    op.create_check_constraint(
        "ck_artifacts_citation_has_message",
        "artifacts",
        "kind <> 'citation' OR message_id IS NOT NULL",
    )


def downgrade() -> None:
    """Downgrade schema.

    Citations are rebuilt into the payload they had. Charts cannot be — nothing
    stored them in that form — so they are dropped, which is the same thing the
    upgrade did to them and is safe for the same reason.
    """
    op.drop_constraint("ck_artifacts_citation_has_message", "artifacts", type_="check")
    op.add_column(
        "artifacts",
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE artifacts a SET payload = jsonb_build_object(
            'kind', 'citation',
            'paper_id', c.paper_id::text,
            'preferred_style', c.preferred_style,
            'style_display', c.style_display,
            'method', c.method,
            'confidence', to_jsonb(c.confidence),
            'missing_fields', to_jsonb(c.missing_fields),
            'data', jsonb_build_object(
                'paper_id', c.paper_id::text,
                'title', c.title,
                'authors', to_jsonb(c.authors),
                'publish_date', c.publish_date,
                'journal', c.journal,
                'publisher', c.publisher,
                'doi', c.doi
            )
        )
        FROM citation_artifacts c
        WHERE c.id = a.id
        """
    )
    op.execute("DELETE FROM artifacts WHERE payload IS NULL")
    op.alter_column("artifacts", "payload", nullable=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chart_values_record_id"), table_name="chart_values")
    op.drop_table("chart_values")
    op.drop_index(op.f("ix_chart_records_paper_id"), table_name="chart_records")
    op.drop_index(op.f("ix_chart_records_chart_id"), table_name="chart_records")
    op.drop_table("chart_records")
    op.drop_index(op.f("ix_chart_fields_chart_id"), table_name="chart_fields")
    op.drop_table("chart_fields")
    op.drop_index(
        op.f("ix_chart_excluded_papers_chart_id"), table_name="chart_excluded_papers"
    )
    op.drop_table("chart_excluded_papers")
    op.drop_index(
        op.f("ix_citation_artifacts_paper_id"), table_name="citation_artifacts"
    )
    op.drop_table("citation_artifacts")
    op.drop_table("chart_artifacts")
    # ### end Alembic commands ###
