"""add field_provenance and trace

Revision ID: 721fedd80cdd
Revises: b7f5658668f6
Create Date: 2026-05-29 03:42:32.214788+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "721fedd80cdd"
down_revision: Union[str, None] = "b7f5658668f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "papers",
        sa.Column(
            "field_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "field_provenance")
    op.drop_column("messages", "trace")
    # ### end Alembic commands ###
