"""add referrals

Revision ID: c07332ef32e2
Revises: 0ceda25c2234
Create Date: 2026-05-12 19:16:55.308736+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c07332ef32e2"
down_revision: Union[str, None] = "0ceda25c2234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_referral_codes_code"), "referral_codes", ["code"], unique=True
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_user_id", sa.UUID(), nullable=False),
        sa.Column("referee_user_id", sa.UUID(), nullable=False),
        sa.Column("code_used", sa.String(length=16), nullable=False),
        sa.Column("attribution_method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("converted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credit_available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("referrer_credit_cents", sa.Integer(), nullable=False),
        sa.Column("referee_coupon_id", sa.String(), nullable=True),
        sa.Column("stripe_balance_transaction_id", sa.String(), nullable=True),
        sa.Column("fraud_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "referrer_user_id <> referee_user_id",
            name="check_referral_no_self_referral",
        ),
        sa.ForeignKeyConstraint(["referee_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referee_user_id"),
    )
    op.create_index(
        op.f("ix_referrals_referrer_user_id"),
        "referrals",
        ["referrer_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_referrals_status"), "referrals", ["status"], unique=False)
    op.add_column(
        "users",
        sa.Column("referral_toast_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referral_toast_seen_at")
    op.drop_index(op.f("ix_referrals_status"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_referrer_user_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_referral_codes_code"), table_name="referral_codes")
    op.drop_table("referral_codes")
    # ### end Alembic commands ###
