"""google oauth state

Tracks in-flight Google sign-ins so the callback can reject forged states and
recognise a replayed authorization code instead of burning it.

Revision ID: 8c89f2444587
Revises: db994ff97eea
Create Date: 2026-08-29 17:23:41.316342+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c89f2444587"
down_revision: Union[str, None] = "db994ff97eea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_oauth_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("was_new_user", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_google_oauth_state_state"),
        "google_oauth_state",
        ["state"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_google_oauth_state_state"), table_name="google_oauth_state")
    op.drop_table("google_oauth_state")
    # ### end Alembic commands ###
