"""add artifacts table

Revision ID: 6d888f7203ba
Revises: 721fedd80cdd
Create Date: 2026-06-01 22:05:02.197019+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d888f7203ba"
down_revision: Union[str, None] = "721fedd80cdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_artifacts_message_id", "artifacts", ["message_id"], unique=False
    )
    op.create_index(
        "ix_artifacts_scope",
        "artifacts",
        ["scope_type", "scope_id", "kind", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifacts_user_id"), "artifacts", ["user_id"], unique=False
    )
    op.drop_column("messages", "bucket")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "bucket",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_artifacts_user_id"), table_name="artifacts")
    op.drop_index("ix_artifacts_scope", table_name="artifacts")
    op.drop_index("ix_artifacts_message_id", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
