"""project title

Revision ID: 7d0f8cddd5db
Revises: cfd4f68e33b7
Create Date: 2026-08-08 23:34:37.822683+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d0f8cddd5db"
down_revision: Union[str, None] = "cfd4f68e33b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("project", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("project", "title", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
